### ISSUE TITLE
cool

### ISSUE THREAD

**Issue by aquynh** [Carbonara-Project/Guanciale#1]
this looks cool, but what is that "Carbonara" project?

keep it up, cheers!

**Comment by andreafioraldi** [comment]
Hi,
I started with some friends to develop a web platform dedicated to malware analysts as a college project.
We are at the first lines of code and in this repo there is the client who will collect data from databases of various disassemblers (at the moment only radare and we are working to add IDA) and send it to our server.

We are italians and [carbonara](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http%3A%2F%2Fricette.giallozafferano.it%2FSpaghetti-alla-Carbonara.html) is a typical food of Rome (pasta with pecorino cheese, bacon and eggs), a good name for a software.
